{{- if .Values.artemis.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.artemis.namespace }}
  labels:
    istio-injection: enabled
    domain: artemis
    mesh: sophia-artemis
    environment: {{ .Values.global.environment }}
  annotations:
    description: "Artemis domain services with automatic Istio sidecar injection"
{{- end }}
---
{{- if .Values.sophia.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sophia.namespace }}
  labels:
    istio-injection: enabled
    domain: sophia
    mesh: sophia-artemis
    environment: {{ .Values.global.environment }}
  annotations:
    description: "Sophia domain services with automatic Istio sidecar injection"
{{- end }}
---
{{- if .Values.sharedServices.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sharedServices.namespace }}
  labels:
    istio-injection: enabled
    domain: shared
    mesh: sophia-artemis
    environment: {{ .Values.global.environment }}
  annotations:
    description: "Shared services accessible by both domains"
{{- end }}
