imports:
  - shared

values:
  environment: staging

  # Staging-specific overrides
  infrastructure:
    redis:
      max_memory_mb: 1024
      max_connections: 75
      cluster_enabled: false
      ssl_verify: true
      backup_enabled: true
      backup_retention_days: 7

    vector_db:
      replication_factor: 1
      backup_enabled: true
      backup_retention_days: 14
      performance_optimization: balanced

  # Staging LLM Provider Keys (rotated versions of dev keys for security)
  llm_providers:
    portkey:
      api_key:
        fn::secret: staging-portkey-key
      base_url: https://api.portkey.ai/v1
      virtual_keys:
        openai:
          fn::secret: staging-openai-vk
        anthropic:
          fn::secret: staging-anthropic-vk
        deepseek:
          fn::secret: staging-deepseek-vk

  # Staging security enhancements
  security:
    api_key_rotation_days: 60
    session_timeout_minutes: 30
    max_failed_attempts: 5
    ip_whitelist_enabled: true
    rate_limiting:
      enabled: true
      requests_per_minute: 500
      burst_limit: 1000

  # Staging monitoring
  monitoring:
    metrics_enabled: true
    tracing_enabled: true
    profiling_enabled: false
    alert_webhooks:
      - url: https://hooks.slack.com/services/staging-alerts

  # Application settings for staging
  application:
    debug: false
    log_level: info
    hot_reload: false
    cors_origins:
      - https://staging.sophia-intel-ai.com
      - https://staging-api.sophia-intel-ai.com
    websocket:
      max_connections: 50
    api:
      rate_limit_per_minute: 500
      timeout_seconds: 45

  # Load testing configuration
  load_testing:
    enabled: true
    max_concurrent_users: 50
    test_duration_minutes: 30
    ramp_up_time_minutes: 5
