system_config:
  sophia_ui_port: 3000
  sophia_api_port: 8003
  builder_agno_port: 8005
  mcp_gateway_port: 8080
  mcp_memory_port: 8081
  mcp_git_port: 8082
  mcp_context_port: 8083
  mcp_index_port: 8084
  environment: development
  node_env: development
  app_env: development
  debug: false
  log_level: INFO
  use_portkey_routing: true
  enable_fallback: true
  enable_load_balancing: true
  local_dev_mode: true
  application_name: Sophia Intelligence Platform
  workspace_path: /Users/lynnmusil/sophia-intel-ai
  workspace_name: sophia
  read_only: false
ai_providers:
  OPENAI_API_KEY: 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
  ANTHROPIC_API_KEY: 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
  USE_PORTKEY_ROUTING: 'true'
  AGNO_API_KEY: phi-0cnOaV2N-MKID0LJTszPjAdj7XhunqMQFG4IwLPG9dI
  OPENROUTER_API_KEY: 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
  ELEVEN_LABS_API_KEY: sk_0b68a8ac28119888145589965bf097211889379a3da2ad41
  ELEVENLABS_API_KEY: sk_0b68a8ac28119888145589965bf097211889379a3da2ad41
  MEM0_API_KEY: m0-migu5eMnfwT41nhTgVHsCnSAifVtOf3WIFz2vmQc
  MEM0_ACCOUNT_ID: org_gHuEO2H7ymIIgivcWeKI2psRFHUnbZ54RQNYVb4T
  MEM0_ACCOUNT_NAME: scoobyjava-default-org
  HUGGINGFACE_API_TOKEN: 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
  ASSEMBLY_API_KEY: 915990f9d7b64eb2bf8fa49b364ffa85
  STABILITY_API_KEY: sk-d3ym0y0RKM841TtSRLst4LNcGc5Ke4WMNLnjmKLcLtQqkVy5
  EDEN_AI_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDE1M2M3ZmMtMTUyMi00NmNiLTg3YjMtNzljZjI4NjQ3YmFiIiwidHlwZSI6ImFwaV90b2tlbiJ9.MFluGVw2X4-Q91KssMyM-4u7ERGqNtdG6n_14OwURwI
  GEMINI_API_KEY: AIzaSyA0rewcfUHo87WMEz4a8Og1eAWTslxlgEE
  GROQ_API_KEY: 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
  DEEPSEEK_API_KEY: sk-c8a5f1725d7b4f96b29a3d041848cb74
  MISTRAL_API_KEY: jCGVZEeBzppPH0pPVL0vxRCPnZuWL90i
  GROK_API_KEY: xai-4WmKCCbqXhuxL56tfrCxaqs3N84fcLVirQG0NIb0NB6ViDPnnvr3vsYOBwpPKpPMzW5UMuHqf1kv87m3
  XAI_API_KEY: xai-4WmKCCbqXhuxL56tfrCxaqs3N84fcLVirQG0NIb0NB6ViDPnnvr3vsYOBwpPKpPMzW5UMuHqf1kv87m3
  TOGETHER_AI_API_KEY: tgp_v1_HE_uluFh-fELZDmEP9xKZXuSBT4a8EHd6s9CmSe5WWo
  PERPLEXITY_API_KEY: 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
  PORTKEY_API_KEY: nYraiE8dOR9A1gDwaRNpSSXRkXBc
  PORTKEY_VIRTUAL_KEYS: anthropic-vk-b42804,deepseek-vk-24102f,groq-vk-6b9b52,openai-vk-190a60,perplexity-vk-56c172,together-ai-670469,vkj-openrouter-cc4151,xai-vk-e65d0f
  AIMLAPI_API_KEY: 562d964ac0b54357874b01de33cb91e9
  AIMLAPI_KEY: 562d964ac0b54357874b01de33cb91e9
  AGNO_API_IMAGE: ghcr.io/agno-agi/agent-api:v1.0.0
  AGNO_UI_IMAGE: ghcr.io/agno-agi/sophia-intel-app:v1.0.0
  DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY}
  PORTKEY_BASE_URL: https://api.portkey.ai/v1
  PORTKEY_VK_DEEPSEEK: deepseek-vk-24102f
  PORTKEY_VK_OPENAI: openai-vk-190a60
  PORTKEY_VK_ANTHROPIC: anthropic-vk-b42804
  PORTKEY_VK_OPENROUTER: vkj-openrouter-cc4151
  PORTKEY_VK_PERPLEXITY: perplexity-vk-56c172
  PORTKEY_VK_GROQ: groq-vk-6b9b52
  PORTKEY_VK_MISTRAL: mistral-vk-f92861
  PORTKEY_VK_XAI: xai-vk-e65d0f
  PORTKEY_VK_TOGETHER: together-ai-670469
  PORTKEY_VK_COHERE: cohere-vk-496fa9
  PORTKEY_VK_GITHUB: github-vk-a5b609
  PORTKEY_VK_STABILITY: stability-vk-a575fb
  PORTKEY_VK_MILVUS: milvus-vk-34fa02
  PORTKEY_VK_QDRANT: qdrant-vk-d2b62a
  PORTKEY_DEFAULT_PROVIDER: openai
  PORTKEY_DEFAULT_MODEL: gpt-4o-mini
  PORTKEY_DEFAULT_TEMPERATURE: '0.2'
  PORTKEY_DEFAULT_MAX_TOKENS: '4000'
  PORTKEY_CACHE_ENABLED: 'true'
  PORTKEY_CACHE_TTL: '3600'
  PORTKEY_CACHE_MODE: semantic
  PORTKEY_RETRY_ATTEMPTS: '3'
  PORTKEY_RETRY_DELAY: '1000'
  PORTKEY_RETRY_EXPONENTIAL_BACKOFF: 'true'
  PORTKEY_GUARDRAILS_ENABLED: 'true'
  PORTKEY_GUARDRAILS_PII_REDACTION: 'true'
  PORTKEY_LOG_LEVEL: info
  PORTKEY_LOG_REQUESTS: 'true'
  PORTKEY_LOG_RESPONSES: 'false'
  PORTKEY_TRACK_COSTS: 'true'
  PORTKEY_COST_ALERT_THRESHOLD: '10.00'
  ANTHROPIC_BETA_VERSION: bedrock-2023-05-31
  DEEPSEEK_BASE_URL: https://api.deepseek.com/v1
  PORTKEY_REQUEST_TIMEOUT: '30000'
  PORTKEY_CONNECTION_POOLING: 'true'
  PORTKEY_MAX_CONNECTIONS: '10'
  PORTKEY_LOAD_BALANCE_STRATEGY: round-robin
  PORTKEY_HEALTH_CHECK_INTERVAL: '60000'
  PORTKEY_CUSTOM_HEADERS: '{"X-Source": "sophia-intel-ai"}'
business_integrations:
  SLACK_BOT_TOKEN: xoxb-293968207940-9492433757667-YAplHFRnTfeV6UCaY7gWLCIo
  SLACK_APP_TOKEN: xapp-1-A09EH9DKDPX-9500784360276-673c418f1ec0778483b4e1676529dc040cc1917e644b34536d3565a8de21efaa
  GONG_ACCESS_KEY: TV33BPZ5UN45QKZCZ2UCAKRXHQ6Q3L5N
  GONG_CLIENT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjIwNTQxNTA4ODUsImFjY2Vzc0tleSI6IlRWMzNCUFo1VU40NVFLWkNaMlVDQUtSWEhRNlEzTDVOIn0.zgPvDQQIvU1kvF_9ctjcKuqC5xKhlpZo7MH5v7AYufU
  GONG_API_URL: https://api.gong.io/v2
  SALESFORCE_ACCESS_TOKEN: 6Cel800DDn000006Cu0y888Ux0000000MrlQC4spG19TPoqHKbMqJgoE535XYy6jdku0a8STJwI45vcRKiu1gsfm4TtDKbtZKXEBchnXJbw
  HUBSPOT_API_KEY: pat-na1-c1671bea-646a-4a61-a2da-33bd33528dc7
  HUBSPOT_ACCESS_TOKEN: pat-na1-c1671bea-646a-4a61-a2da-33bd33528dc7
  HUBSPOT_CLIENT_SECRET: 6080317b-15f9-4a73-b151-a0731616ca50
  LOOKER_CLIENT_ID: jChsJPr9FDP2qSCYyyD2
  LOOKER_CLIENT_SECRET: kXxhgscT87fstFBcPRTNj733
  LOOKER_BASE_URL: https://YOUR_INSTANCE.looker.com
  LOOKER_API_VERSION: '4.0'
  LINEAR_API_KEY: lin_api_gF8bCZPVYz02YKUGp1yqqkGJOnJ6XICaK2bdftIp
  ASANA_API_TOKEN: 2/1202141391816423/1210641884736129:b164f0c8b881738b617e46065c4b9291
  ASANA_PAT_TOKEN: 2/1202141391816423/1210641884736129:b164f0c8b881738b617e46065c4b9291
  ASANA_PAT: 2/1210550650060115/1211296760092597:af91983306d2e9169c1dad4dcff59b8e
  LATTICE_API_KEY: 8aea9524-1849-418f-bec4-eb2d1153449f
  AIRTABLE_API_KEY: patuojzcFCHtcwkH3.2d1b20fd467f58319534f2abb02899d32390e1db02ffa226aa08c084bd21ce5d
  AIRTABLE_ACCESS_TOKEN: patuojzcFCHtcwkH3.2d1b20fd467f58319534f2abb02899d32390e1db02ffa226aa08c084bd21ce5d
  AIRTABLE_BASE_ID: appYOUR_BASE_ID
  AIRTABLE_TABLE_IDS: tblbSL8gS3oSShkTs,tbl1Qkk3AEx3PQhLL
  NETSUITE_AUTH_METHOD: oauth2
  SLACK_CLIENT_ID: '293968207940.84057706630910663091'
  SLACK_CLIENT_SECRET: 778e2fb5b026f97587210602acfe1e0b
  SLACK_REFRESH_TOKEN: xoxe-1-My0xLTI5Mzk2ODIwNzk0MC04NDI5MzkxMDk3NzI4LTgzOTIwNDIxNTQzNTktODlkNTI0YmI4ZDQ4MGNlMWMxNTNkMzUwMzBiMGFkNTNlYzZjYzljYTM5Mzc2YmZjMmQ1Y2Y2YWM5NDFjZWYyNw
  SLACK_SIGNING_SECRET: f06e529023c037b556159eef897f2cd6
  SLACK_SOCKET_TOKEN: xapp-1-A09EH9DKDPX-9500784360276-673c418f1ec0778483b4e1676529dc040cc1917e644b34536d3565a8de21efaa
  SLACK_VERIFICATION_TOKEN: 8yhl8QLHfeXrQwSpYZcl0fEi
  SLACK_API_TOKEN: xoxp-YOUR_SLACK_USER_TOKEN
  SLACK_USER_TOKEN: xoxp-YOUR_SLACK_USER_TOKEN
  SALESFORCE_INSTANCE_URL: https://YOUR_INSTANCE.salesforce.com
  HUBSPOT_API_TOKEN: pat-na1-c1671bea-646a-4a61-a2da-33bd33528dc7
  AIRTABLE_API_TOKEN: patuojzcFCHtcwkH3.2d1b20fd467f58319534f2abb02899d32390e1db02ffa226aa08c084bd21ce5d
databases:
  WEAVIATE_API_KEY: VMKjGMQUnXQIDiFOciZZOhr7amBfCHMh7hNf
  WEAVIATE_ADMIN_API_KEY: VMKjGMQUnXQIDiFOciZZOhr7amBfCHMh7hNf
  WEAVIATE_REST_ENDPOINT: w6bigpoxsrwvq7wlgmmdva.c0.us-west3.gcp.weaviate.cloud
  WEAVIATE_GRPC_ENDPOINT: grpc-w6bigpoxsrwvq7wlgmmdva.c0.us-west3.gcp.weaviate.cloud
  WEAVIATE_URL: https://w6bigpoxsrwvq7wlgmmdva.c0.us-west3.gcp.weaviate.cloud
  WEAVIATE_LOCAL_URL: http://localhost:8081
  QDRANT_API_KEY: 2d196a4d-a80f-4846-be65-67563bced21f|8aakHwQeR3g5dWbeN4OGCs3FpaxyvkanTDMfbD4eIS_NsLS7nMlS4Q
  QDRANT_URL: https://a2a5dc3b-bf37-4907-9398-d49f5c6813ed.us-west-2-0.aws.cloud.qdrant.io
  QDRANT_CLUSTER_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwiZXhwIjoxNzY1NTkxNjEzfQ.a4uBhUimAhpzdGLLOmSwHwGWF4rAQynEFZG8A9pDHkQ
  NEO4J_URI: bolt://localhost:7687
  NEO4J_CLIENT_ID: jPSJvG4itnj6DHbdUwm9dBTjeimb9wXv
  NEO4J_CLIENT_SECRET: q5XHZu1GOrsJK7bcOByHCNxZy3LrCF3iVg-fVaHLwyj6N5nRFe_Fif-YORMtWfPy
  POSTGRES_URL: postgresql://sophia:sophia_secure_password_2024@postgres:5432/sophia
  POSTGRES_PASSWORD: sophia_secure_password_2024
  POSTGRES_HOST: localhost
  POSTGRES_PORT: '5432'
  POSTGRES_DB: sophia
  POSTGRES_USER: sophia
  REDIS_URL: redis-15014.force172.us-east-1-1.ec2.redns.redis-cloud.com
  REDIS_CLOUD_URL: redis-15014.force172.us-east-1-1.ec2.redns.redis-cloud.com
  REDIS_HOST: redis-15014.fcrce172.us-east-1-1.ec2.redns.redis-cloud.com
  REDIS_PORT: '15014'
  REDIS_USER_API_KEY: S666q3cr9wmzpetc6iud02iqv26774azveodh2pfadrd7pgq8l7
  NEON_API_KEY: napi_r3gsuacduzw44nqdqav1u0hr2uv4bb2if48r8627jkxo7e4b2sxn92wsgf6zlxby
  NEON_PROJECT_ID: rough-union-72390895
  NEON_BRANCH_ID: br-green-firefly-afykrx78
  NEON_API_TOKEN: napi_r3gsuacduzw44nqdqav1u0hr2uv4bb2if48r8627jkxo7e4b2sxn92wsgf6zlxby
  NEON_ENDPOINT: rough-union-72390895.us-west-2.aws.neon.tech
  NEON_HOST: rough-union-72390895.us-west-2.aws.neon.tech
  NEON_DATABASE: sophia
  NEON_PORT: '5432'
  NEON_AUTH_JWKS_URL: https://auth.neon.tech/.well-known/jwks.json
  NEON_DATABASE_URL: postgresql://neondb_owner:npg_KAox7FwSrHu9@ep-rough-dew-af6w48m3.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
  NEXT_PUBLIC_WEAVIATE_URL: http://localhost:8080
  PORT_POSTGRES: '5432'
  PORT_REDIS: '6379'
  PORT_WEAVIATE: '8080'
  PORT_NEO4J_HTTP: '7474'
  PORT_NEO4J_BOLT: '7687'
infrastructure:
  GITHUB_TOKEN: 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
  GITHUB_PAT: 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
  GITHUB_ORG: pay-ready
  GITHUB_USERNAME: scoobyjava
development:
  SENTRY_API_TOKEN: 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
  ARIZE_API_KEY: ak-0ea39c4f-d87e-492c-afa3-cc34b69dfdba-2cqWixdMIgv9RqR8DWTqkIGugAicXQ0eu
  ARIZE_SPACE_ID: U3BhY2U6MjIzNTA6UlllNQ==
  LANGCHAIN_API_KEY: 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
  N8N_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2Y4NTVkMi05ODIwLTQ2ZmMtYjlhMS1kMjdlN2ZhMGQ3MDIiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzUwMjgyMjU5LCJleHAiOjE3NTgwMDYwMDB9.5uLdSTZdIwlSld3WpVGC0TVm97vvzXs3y44FNeRm3N8
  N8N_INSTANCE_URL: https://scoobyjava.app.n8n.cloud
  N8N_USERNAME: admin
  N8N_WEBHOOK_URL: https://scoobyjava.app.n8n.cloud/webhook/gong-webhook
  TELEGRAM_API_KEY: 8431354714:AAGp0HXFAoCYBnjyiZnqGoVVd8SBgCnujE0
  JWT_SECRET: sophia_super_secure_jwt_secret_key_for_production_2024_0987654321
  API_SECRET_KEY: sophia_api_secret_key_2024_production_deployment
  ENCRYPTION_KEY: sophia_encryption_key_2024_ultra_secure
  MCP_SECRET_KEY: sophia_mcp_secret_key_2024
  MCP_API_KEY: sophia-mcp-key
security:
  CEO_KNOWLEDGE_BASE_API_KEY: patuojzcFCHtcwkH3.2d1b20fd467f58319534f2abb02899d32390e1db02ffa226aa08c084bd21ce5d
  TAVILY_API_KEY: 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
  EXA_API_KEY: fdf07f38-34ad-44a9-ab6f-74ca2ca90fd4
  BRAVE_API_KEY: BSApz0194z7SG6DplmVozl7ttFOi0Eo
  SERPER_API_KEY: 7b616d4bf53e98d9169e89c25d6f4bf4389a9ed5
  NEWSDATA_API_KEY: pub_7c0992e0408246a88af169733912e4e5
  VIDEOSDK_API_KEY: 65e3ae27-8e14-497e-bfff-89392558fbb6
  VIDEOSDK_SECRET_KEY: 38fdf5d879b47804a99fe23784abc3355697b83b33dd5e61a0dcccfa4d923f3c
misc:
  ENABLE_FALLBACK: 'true'
  ENABLE_LOAD_BALANCING: 'true'
  MS_GRAPH_CERT_THUMBPRINT: 7E68655821A51480C60939D7AE26AC6FC0F5A9E2
  CEO_KNOWLEDGE_BASE_ID: appYOUR_CEO_KB_BASE_ID
  NODE_ENV: development
  APP_ENV: development
  ENVIRONMENT: development
  LOCAL_DEV_MODE: 'true'
  LOG_LEVEL: INFO
  REQUEST_TIMEOUT: '30'
  MAX_RETRIES: '2'
  AGENT_API_PORT: '8003'
  TELEMETRY_PORT: '5003'
  UI_PORT: '3000'
  CLI_WS_PORT: '8083'
  MCP_MEMORY_HOST: 0.0.0.0
  MCP_MEMORY_PORT: '8081'
  MCP_FS_SOPHIA_PORT: '8082'
  MCP_FILE_PORT: '8082'
  MCP_WEB_PORT: '8083'
  MCP_GIT_PORT: '8084'
  MCP_LOG_LEVEL: INFO
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:${PORT_API}}
  NEXT_PUBLIC_TELEMETRY_URL: http://localhost:5003
  WS_URL: ws://localhost:8083
  NEXT_PUBLIC_SHOW_METRICS_DEBUG: '1'
  NEXT_PUBLIC_USE_REALTIME_MANAGER: '1'
  NEXT_PUBLIC_USE_UNIFIED_CHAT: '1'
  MCP_SERVER_URL: http://localhost:8004
  MCP_FS_BASE_URL: http://mcp-filesystem:8082
  # MCP_FS_ARTEMIS_PORT removed (Sophia decommissioned)
  SOPHIA_PATH: $HOME/sophia-cli
  WORKSPACE_PATH: /app
  WORKSPACE_NAME: sophia
  READ_ONLY: 'false'
  APPLICATION_ID: 82329689-C871-456F-8AA0-96DBDF5B0275
  NAME: '"Sophia Integration"GITHUB_USERNAME=scoobyjava'
  PORT_API: ${PORT_API:-8003}
  PORT_WS: ${PORT_WS:-8083}
  PORT_UI: ${PORT_UI:-3000}
  NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-ws://localhost:${PORT_WS}}
  API_BASE_URL: ${API_BASE_URL:-http://localhost:${PORT_API}}
  VOICE_DEPLOYMENT_MODE: hybrid
  VOICE_HOST: 0.0.0.0
  VOICE_PORT: '8443'
  VOICE_MODELS_PATH: /Users/lynnmusil/sophia-intel-ai/models
  VOICE_LOGS_PATH: /Users/lynnmusil/sophia-intel-ai/logs
  WISPR_FLOW_ENABLED: 'true'
  WISPR_FLOW_MODE: pro
  BRIDGE_PORT: '8004'
  API_PORT: '8003'
  NEXT_PUBLIC_API_BASE: http://localhost:8000
  NEXT_PUBLIC_API_HOST: localhost
  NEXT_PUBLIC_API_PORT: '8000'
  NEXT_PUBLIC_WS_HOST: localhost
  NEXT_PUBLIC_WS_PORT: '8000'
  NEXT_PUBLIC_MCP_MEMORY_URL: http://localhost:8081
  NEXT_PUBLIC_MCP_FILESYSTEM_URL: http://localhost:8082
  NEXT_PUBLIC_MCP_GIT_URL: http://localhost:8084
  PORT_MCP_MEMORY: '8081'
  PORT_MCP_FILESYSTEM: '8082'
  PORT_MCP_GIT: '8084'
  PORT_PROMETHEUS: '9090'
  PORT_GRAFANA: '3001'
