# Documentation Generation Configuration
# Automated documentation system for Sophia AI platform

# Source directories to analyze for code documentation
source_dirs:
  - "backend/"
  - "asip/"
  - "agents/"
  - "mcp_servers/"
  - "frontend/src/"
  - "infrastructure/"

# Output directory for generated documentation
output_dir: "docs/generated"

# Documentation formats to generate
formats:
  - "markdown"
  - "html"

# Include private methods and classes in documentation
include_private: false

# Include test files in documentation
include_tests: true

# API specification files to parse
api_spec_paths:
  - "docs/api/unified-mcp-server.md"
  - "docs/api/sophia-swarm-orchestrator.md"
  - "docs/api/base-mcp-server-library.md"
  - "docs/api/business-intelligence-server.md"
  - "docs/api/mem0-memory-server.md"

# Optional customization paths
template_dir: "docs/templates"
custom_css: "docs/assets/custom.css"
logo_path: "docs/assets/sophia-ai-logo.png"

# Additional configuration
generation:
  # Automatically update documentation on code changes
  auto_update: true
  
  # Frequency for automated updates (cron format)
  update_schedule: "0 2 * * *"  # Daily at 2 AM
  
  # Git integration
  git_integration:
    enabled: true
    commit_message: "docs: auto-update generated documentation"
    branch: "main"
  
  # Notification settings
  notifications:
    enabled: true
    channels:
      - type: "slack"
        webhook_url: "${SLACK_WEBHOOK_URL}"
      - type: "email"
        recipients: ["dev-team@sophia-intel.ai"]

# Quality checks
quality_checks:
  # Minimum documentation coverage threshold
  min_coverage: 80
  
  # Check for broken links
  check_links: true
  
  # Validate API specifications
  validate_api_specs: true
  
  # Check for outdated documentation
  check_freshness: true
  max_age_days: 30

# Advanced features
advanced:
  # Generate interactive API playground
  generate_playground: true
  
  # Include performance metrics in docs
  include_performance_metrics: true
  
  # Generate architectural diagrams
  generate_diagrams: true
  
  # Multi-language support
  languages:
    - "en"
    - "es"  # Spanish
    - "fr"  # French
  
  # Search integration
  search:
    enabled: true
    provider: "algolia"
    index_name: "sophia-ai-docs"

# Deployment configuration
deployment:
  # Deploy to GitHub Pages
  github_pages:
    enabled: true
    repository: "sophia-ai/documentation"
    branch: "gh-pages"
  
  # Deploy to custom domain
  custom_domain:
    enabled: false
    url: "docs.sophia-intel.ai"
  
  # CDN integration
  cdn:
    enabled: false
    provider: "cloudflare"