app = "sophia-weaviate"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "semitechnologies/weaviate:1.32.1"

[env]
  QUERY_DEFAULTS_LIMIT = "25"
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = "true"
  PERSISTENCE_DATA_PATH = "/var/lib/weaviate"
  ENABLE_MODULES = "text2vec-openai,text2vec-cohere,text2vec-huggingface,generative-openai,qna-openai"
  DEFAULT_VECTORIZER_MODULE = "text2vec-openai"
  VECTOR_INDEX_TYPE = "hnsw"
  ENABLE_VECTOR_QUANTIZATION = "true"
  QUANTIZATION_TYPE = "rq"
  CLUSTER_HOSTNAME = "node1"
  ENABLE_MULTI_TENANCY = "true"
  AUTO_TENANT_CREATION = "true"
  GOGC = "100"

[experimental]
  auto_rollback = true
  enable_consul = true

[services]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/v1/.well-known/ready"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[mounts]
  source = "sophia_weaviate_data"
  destination = "/data"
  initial_size = "20gb"

[[vm]]
  cpu_kind = "shared"
  cpus = 2.0
  memory_mb = 2048

[scaling]
  min_machines_running = 1
  max_machines_running = 4

  [[scaling.metrics]]
    type = "cpu"
    target = 70

  [[scaling.metrics]]
    type = "memory"
    target = 75