app = "sophia-ui"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "./agent-ui/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NEXT_PUBLIC_API_URL = "https://sophia-api.fly.dev"
  NEXT_PUBLIC_BRIDGE_URL = "https://sophia-bridge.fly.dev"
  NEXT_PUBLIC_DEFAULT_ENDPOINT = "https://sophia-api.fly.dev"
  NEXT_PUBLIC_PLAYGROUND_URL = "https://sophia-api.fly.dev"
  NEXT_PUBLIC_USE_BRIDGE = "true"
  NEXT_PUBLIC_ENABLE_ANALYTICS = "true"
  NEXT_PUBLIC_ENVIRONMENT = "production"
  NEXT_PUBLIC_ENABLE_CONSENSUS_UI = "true"
  NEXT_PUBLIC_ENABLE_MEMORY_DEDUP_UI = "true"
  NEXT_PUBLIC_ENABLE_SWARM_MONITORING = "true"

[experimental]
  auto_rollback = true
  enable_consul = true

[services]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[mounts]
  source = "sophia_ui_data"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  cpu_kind = "shared"
  cpus = 1.0
  memory_mb = 1024

[scaling]
  min_machines_running = 1
  max_machines_running = 6

  [[scaling.metrics]]
    type = "cpu"
    target = 70

  [[scaling.metrics]]
    type = "memory"
    target = 75