app = "sophia-vector"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "./pulumi/vector-store/Dockerfile"

[env]
  VECTOR_STORE_PORT = "8005"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
  LOCAL_DEV_MODE = "false"
  WEAVIATE_URL = "http://sophia-weaviate.internal:8080"
  EMBEDDING_TIER_S_MODEL = "voyage-3-large"
  EMBEDDING_TIER_A_MODEL = "cohere/embed-multilingual-v3.0"
  EMBEDDING_TIER_B_MODEL = "BAAI/bge-base-en-v1.5"
  PORTKEY_BASE_URL = "https://api.portkey.ai/v1"
  USE_REAL_APIS = "true"
  ENABLE_API_VALIDATION = "true"
  ENABLE_EMBEDDING_CACHE = "true"

[experimental]
  auto_rollback = true
  enable_consul = true

[services]
  protocol = "tcp"
  internal_port = 8005
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[mounts]
  source = "sophia_vector_data"
  destination = "/data"
  initial_size = "10gb"

[[vm]]
  cpu_kind = "shared"
  cpus = 2.0
  memory_mb = 2048

[scaling]
  min_machines_running = 1
  max_machines_running = 12

  [[scaling.metrics]]
    type = "cpu"
    target = 70

  [[scaling.metrics]]
    type = "memory"
    target = 75