# Fly.io Configuration for Sophia Weaviate v1.32+
app = "sophia-weaviate"
primary_region = "sjc"  # San Jose - closest to California
kill_signal = "SIGINT"
kill_timeout = "10s"

[build]
  image = "semitechnologies/weaviate:1.32.1"

[env]
  QUERY_DEFAULTS_LIMIT = "25"
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = "true"
  PERSISTENCE_DATA_PATH = "/var/lib/weaviate"
  
  # v1.32+ Advanced Features
  ENABLE_MODULES = "text2vec-openai,text2vec-cohere,text2vec-huggingface,generative-openai,qna-openai"
  DEFAULT_VECTORIZER_MODULE = "text2vec-openai"
  
  # RQ Compression (75% memory reduction)
  VECTOR_INDEX_TYPE = "hnsw"
  ENABLE_VECTOR_QUANTIZATION = "true"
  QUANTIZATION_TYPE = "rq"
  
  # Performance optimizations
  CLUSTER_HOSTNAME = "node1"
  CLUSTER_GOSSIP_BIND_PORT = "7946"
  CLUSTER_DATA_BIND_PORT = "7947"
  
  # Multi-tenancy support
  ENABLE_MULTI_TENANCY = "true"
  AUTO_TENANT_CREATION = "true"
  
  # Memory optimization
  GOGC = "100"

[experimental]
  auto_rollback = true
  enable_consul = true

[services]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false  # Keep Weaviate always running
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.ports]]
    port = 50051
    handlers = ["http"]  # gRPC over HTTP/2 for high-performance operations
  
  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "2s"
    restart_limit = 6

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/v1/.well-known/ready"
    protocol = "http"
    timeout = "5s"
    tls_skip_verify = false
    
    [services.http_checks.headers]
      X-Health-Check = "fly.io"

# Persistent storage for Weaviate data
[mounts]
  source = "weaviate_data"
  destination = "/var/lib/weaviate"
  initial_size = "20gb"

# Metrics endpoint for monitoring
[metrics]
  port = 9091
  path = "/metrics"

# Machine configuration for vector operations
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
  
# Auto-scaling configuration
[scaling]
  min_machines_running = 1
  max_machines_running = 4
  
  [[scaling.metrics]]
    type = "cpu"
    target = 70
  
  [[scaling.metrics]]
    type = "memory"
    target = 75