app = "sophia-mcp"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "./pulumi/mcp-server/Dockerfile"

[env]
  MCP_SERVER_PORT = "8004"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
  LOCAL_DEV_MODE = "false"
  WEAVIATE_URL = "http://sophia-weaviate.internal:8080"
  USE_REAL_APIS = "true"
  ENABLE_API_VALIDATION = "true"
  ENABLE_MCP_PROTOCOL = "true"

[experimental]
  auto_rollback = true
  enable_consul = true

[services]
  protocol = "tcp"
  internal_port = 8004
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[mounts]
  source = "sophia_mcp_data"
  destination = "/data"
  initial_size = "5gb"

[[vm]]
  cpu_kind = "shared"
  cpus = 2.0
  memory_mb = 2048

[scaling]
  min_machines_running = 1
  max_machines_running = 8

  [[scaling.metrics]]
    type = "cpu"
    target = 70

  [[scaling.metrics]]
    type = "memory"
    target = 75