app = "sophia-bridge"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.agno-bridge.production"

[env]
  PORT = "7777"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
  LOCAL_DEV_MODE = "false"
  UNIFIED_API_URL = "http://sophia-api.internal:8003"
  MCP_SERVER_URL = "http://sophia-mcp.internal:8004"
  VECTOR_STORE_URL = "http://sophia-vector.internal:8005"
  ENABLE_CORS = "true"
  CORS_ORIGINS = "*"
  DEBUG = "false"
  USE_REAL_APIS = "true"
  ENABLE_API_VALIDATION = "true"

[experimental]
  auto_rollback = true
  enable_consul = true

[services]
  protocol = "tcp"
  internal_port = 7777
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[mounts]
  source = "sophia_bridge_data"
  destination = "/data"
  initial_size = "2gb"

[[vm]]
  cpu_kind = "shared"
  cpus = 1.0
  memory_mb = 1024

[scaling]
  min_machines_running = 1
  max_machines_running = 8

  [[scaling.metrics]]
    type = "cpu"
    target = 70

  [[scaling.metrics]]
    type = "memory"
    target = 75