SHELL := /bin/bash

# DEPRECATED: Use the root Makefile.
# This trampoline forwards targets to avoid duplication.

.PHONY: %

%:
	@echo "[DEPRECATION] Makefile.dev is deprecated. Use 'make $@' (root Makefile). Forwarding..."
	@$(MAKE) -f Makefile $@
