# Optimized Docker Compose for Artemis Scout Swarm
# Minimal services needed for scout operations

version: "3.8"

services:
  # Redis for L1 cache (lightweight, always needed)
  redis:
    image: redis:7-alpine
    container_name: artemis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M

  # Weaviate for vector storage (optional but recommended)
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: artemis-weaviate
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none" # We handle embeddings externally
      ENABLE_MODULES: "" # Minimal modules for speed
      CLUSTER_HOSTNAME: "node1"
      LIMIT_RESOURCES: "true"
      GOGC: 100 # More aggressive garbage collection
    volumes:
      - weaviate-data:/var/lib/weaviate
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  redis-data:
    driver: local
  weaviate-data:
    driver: local

networks:
  default:
    name: artemis-network
    driver: bridge
