# =============================================================================
# Pulumi ESC Base Environment - Sophia Intel AI
# Shared configuration and encrypted secrets for all environments
# =============================================================================

values:
  # Project Metadata
  project:
    name: sophia-intel-ai
    organization: sophia-intel-ai
    version: "1.0.0"

  # =============================================================================
  # ENCRYPTED SECRETS - All sensitive data
  # =============================================================================
  secrets:
    # Primary LLM Provider APIs
    llm_providers:
      agno_api_key:
        fn::secret: ${AGNO_API_KEY}
      anthropic_api_key:
        fn::secret: ${ANTHROPIC_API_KEY}
      openai_api_key:
        fn::secret: ${OPENAI_API_KEY}
      openrouter_api_key:
        fn::secret: ${OPENROUTER_API_KEY}
      groq_api_key:
        fn::secret: ${GROQ_API_KEY}
      deepseek_api_key:
        fn::secret: ${DEEPSEEK_API_KEY}
      xai_api_key:
        fn::secret: ${XAI_API_KEY}
      gemini_api_key:
        fn::secret: ${GEMINI_API_KEY}
      mistral_api_key:
        fn::secret: ${MISTRAL_API_KEY}
      perplexity_api_key:
        fn::secret: ${PERPLEXITY_API_KEY}

    # Gateway and Router APIs
    gateway:
      portkey_api_key:
        fn::secret: ${PORTKEY_API_KEY}
      portkey_virtual_keys:
        openrouter:
          fn::secret: ${PORTKEY_OPENROUTER_VK}
        anthropic:
          fn::secret: ${PORTKEY_ANTHROPIC_VK}
        together:
          fn::secret: ${PORTKEY_TOGETHER_VK}
        xai:
          fn::secret: ${PORTKEY_XAI_VK}

    # Memory and Vector Stores
    memory:
      weaviate_api_key:
        fn::secret: ${WEAVIATE_API_KEY}
      mem0_api_key:
        fn::secret: ${MEM0_API_KEY}
      mem0_account_id:
        fn::secret: ${MEM0_ACCOUNT_ID}

    # Database Credentials
    databases:
      # PostgreSQL (Neon)
      neon_api_key:
        fn::secret: ${NEON_API_KEY}
      postgres_password:
        fn::secret: ${POSTGRES_PASSWORD}
      neon_password:
        fn::secret: ${NEON_PASSWORD}

      # Redis
      redis_password:
        fn::secret: ${REDIS_PASSWORD}
      redis_user_key:
        fn::secret: ${REDIS_USER_KEY}
      redis_account_key:
        fn::secret: ${REDIS_ACCOUNT_KEY}

    # Infrastructure APIs
    infrastructure:
      pulumi_access_token:
        fn::secret: ${PULUMI_ACCESS_TOKEN}
      fly_api_token:
        fn::secret: ${FLY_API_TOKEN}
      lambda_api_key:
        fn::secret: ${LAMBDA_API_KEY}
      docker_pat:
        fn::secret: ${DOCKER_PAT}
      github_token:
        fn::secret: ${GITHUB_TOKEN}

    # Embedding and Search APIs
    search_data:
      huggingface_token:
        fn::secret: ${HUGGINGFACE_API_TOKEN}
      exa_api_key:
        fn::secret: ${EXA_API_KEY}
      brave_api_key:
        fn::secret: ${BRAVE_API_KEY}
      serper_api_key:
        fn::secret: ${SERPER_API_KEY}
      tavily_api_key:
        fn::secret: ${TAVILY_API_KEY}
      newsdata_api_key:
        fn::secret: ${NEWSDATA_API_KEY}

    # Monitoring and Observability
    observability:
      langchain_api_key:
        fn::secret: ${LANGCHAIN_API_KEY}
      arize_api_key:
        fn::secret: ${ARIZE_API_KEY}
      arize_space_id:
        fn::secret: ${ARIZE_SPACE_ID}

    # Security Keys
    security:
      jwt_secret:
        fn::secret: ${JWT_SECRET}
      api_secret_key:
        fn::secret: ${API_SECRET_KEY}
      neon_auth_jwks_url:
        fn::secret: ${NEON_AUTH_JWKS_URL}

    # Additional Service APIs (100+ third-party integrations)
    services:
      apify_token:
        fn::secret: ${APIFY_API_TOKEN}
      apollo_api_key:
        fn::secret: ${APOLLO_IO_API_KEY}
      asana_token:
        fn::secret: ${ASANA_API_TOKEN}
      assembly_api_key:
        fn::secret: ${ASSEMBLY_API_KEY}
      brightdata_key:
        fn::secret: ${BRIGHTDATA_API_KEY}
      figma_pat:
        fn::secret: ${FIGMA_PAT}
      hubspot_token:
        fn::secret: ${HUBSPOT_ACCESS_TOKEN}
      linear_api_key:
        fn::secret: ${LINEAR_API_KEY}
      notion_api_key:
        fn::secret: ${NOTION_API_KEY}
      telegram_api_key:
        fn::secret: ${TELEGRAM_API_KEY}

  # =============================================================================
  # SHARED CONFIGURATION - Non-sensitive settings
  # =============================================================================
  config:
    # Base Service URLs Templates
    services:
      portkey_base_url: "https://api.portkey.ai/v1"
      openrouter_base_url: "https://openrouter.ai/api/v1"
      anthropic_base_url: "https://api.anthropic.com"
      groq_base_url: "https://api.groq.com/openai/v1"
      lambda_cloud_endpoint: "https://cloud.lambdalabs.com/api/v1"

    # Database Connection Templates
    database_templates:
      postgres:
        port: 5432
        ssl_mode: "require"
        connection_timeout: 30
      redis:
        port: 6379
        connection_timeout: 5
      weaviate:
        port: 8080
        timeout: 30
        batch_size: 100

    # Shared Model Configurations
    models:
      # Standard model pools across environments
      pools:
        fast: ["groq/llama-3.2-90b-text-preview", "openai/gpt-4o-mini"]
        balanced: ["openai/gpt-4o", "anthropic/claude-3.5-sonnet"]
        heavy:
          [
            "anthropic/claude-3.5-sonnet",
            "qwen/qwen-2.5-coder-32b-instruct",
            "openai/gpt-4o",
          ]

      # Embedding tiers
      embeddings:
        tier_s: "voyage-3-large"
        tier_a: "cohere/embed-multilingual-v3.0"
        tier_b: "BAAI/bge-base-en-v1.5"

      # Model fallback chains
      fallback:
        primary: ["anthropic/claude-3.5-sonnet", "openai/gpt-4o"]
        secondary: ["openai/gpt-4o", "groq/llama-3.2-90b-text-preview"]

    # Shared Feature Flags
    features:
      # Core features
      enable_streaming: true
      enable_memory: true
      enable_teams: true
      enable_workflows: true
      enable_apps: true
      enable_evaluation_gates: true
      enable_runner_gate: true
      enable_safety_checks: true

      # Development features
      enable_runner_writes: true
      enable_git_writes: true
      enable_file_writes: true

    # Performance Defaults
    performance:
      max_workers: 10
      timeout_seconds: 120
      max_retries: 3
      batch_size: 10
      parallel_requests: 5

    # Cost Control Defaults
    cost_controls:
      max_tokens_per_request: 4096
      api_rate_limit: 100
      api_rate_window: 60

    # Security Settings
    security:
      cors_enabled: true
      tls_min_version: "1.2"
      request_logging: true

    # Observability Defaults
    observability:
      prometheus_enabled: true
      prometheus_port: 9090
      jaeger_enabled: true
      metrics_enabled: true

# =============================================================================
# ENVIRONMENT VARIABLES EXPORT
# Export all configuration as environment variables for applications
# =============================================================================
environmentVariables:
  # =============================================================================
  # LLM PROVIDER CONFIGURATION
  # =============================================================================

  # Primary Gateway (Portkey)
  OPENAI_BASE_URL: ${config.services.portkey_base_url}
  OPENAI_API_KEY: ${secrets.llm_providers.openai_api_key}
  PORTKEY_API_KEY: ${secrets.gateway.portkey_api_key}
  PORTKEY_BASE_URL: ${config.services.portkey_base_url}

  # Portkey Virtual Keys
  PORTKEY_OPENROUTER_VK: ${secrets.gateway.portkey_virtual_keys.openrouter}
  PORTKEY_ANTHROPIC_VK: ${secrets.gateway.portkey_virtual_keys.anthropic}
  PORTKEY_TOGETHER_VK: ${secrets.gateway.portkey_virtual_keys.together}
  PORTKEY_XAI_VK: ${secrets.gateway.portkey_virtual_keys.xai}

  # Direct Provider APIs
  AGNO_API_KEY: ${secrets.llm_providers.agno_api_key}
  ANTHROPIC_API_KEY: ${secrets.llm_providers.anthropic_api_key}
  OPENROUTER_API_KEY: ${secrets.llm_providers.openrouter_api_key}
  GROQ_API_KEY: ${secrets.llm_providers.groq_api_key}
  DEEPSEEK_API_KEY: ${secrets.llm_providers.deepseek_api_key}
  XAI_API_KEY: ${secrets.llm_providers.xai_api_key}
  GEMINI_API_KEY: ${secrets.llm_providers.gemini_api_key}
  MISTRAL_API_KEY: ${secrets.llm_providers.mistral_api_key}
  PERPLEXITY_API_KEY: ${secrets.llm_providers.perplexity_api_key}

  # =============================================================================
  # MEMORY AND VECTOR STORE CONFIGURATION
  # =============================================================================

  # Weaviate v1.32+ (primary vector store)
  WEAVIATE_API_KEY: ${secrets.memory.weaviate_api_key}
  WEAVIATE_BATCH_SIZE: ${config.database_templates.weaviate.batch_size}
  WEAVIATE_TIMEOUT: ${config.database_templates.weaviate.timeout}

  # MEM0 Integration
  MEM0_API_KEY: ${secrets.memory.mem0_api_key}
  MEM0_ACCOUNT_ID: ${secrets.memory.mem0_account_id}
  MEM0_ACCOUNT_NAME: "scoobyjava-default-org"

  # =============================================================================
  # DATABASE CONFIGURATION
  # =============================================================================

  # PostgreSQL (Neon)
  NEON_API_KEY: ${secrets.databases.neon_api_key}
  POSTGRES_PASSWORD: ${secrets.databases.postgres_password}
  NEON_PASSWORD: ${secrets.databases.neon_password}

  # Redis Configuration
  REDIS_PASSWORD: ${secrets.databases.redis_password}
  REDIS_USER_KEY: ${secrets.databases.redis_user_key}
  REDIS_ACCOUNT_KEY: ${secrets.databases.redis_account_key}

  # =============================================================================
  # INFRASTRUCTURE CONFIGURATION
  # =============================================================================

  # Pulumi & Deployment
  PULUMI_ACCESS_TOKEN: ${secrets.infrastructure.pulumi_access_token}
  FLY_API_TOKEN: ${secrets.infrastructure.fly_api_token}
  LAMBDA_API_KEY: ${secrets.infrastructure.lambda_api_key}
  LAMBDA_CLOUD_ENDPOINT: ${config.services.lambda_cloud_endpoint}

  # Container Registry & Git
  DOCKER_PAT: ${secrets.infrastructure.docker_pat}
  GITHUB_TOKEN: ${secrets.infrastructure.github_token}

  # =============================================================================
  # SEARCH AND DATA APIs
  # =============================================================================

  HUGGINGFACE_API_TOKEN: ${secrets.search_data.huggingface_token}
  EXA_API_KEY: ${secrets.search_data.exa_api_key}
  BRAVE_API_KEY: ${secrets.search_data.brave_api_key}
  SERPER_API_KEY: ${secrets.search_data.serper_api_key}
  TAVILY_API_KEY: ${secrets.search_data.tavily_api_key}
  NEWSDATA_API_KEY: ${secrets.search_data.newsdata_api_key}

  # =============================================================================
  # MONITORING AND OBSERVABILITY
  # =============================================================================

  LANGCHAIN_API_KEY: ${secrets.observability.langchain_api_key}
  ARIZE_API_KEY: ${secrets.observability.arize_api_key}
  ARIZE_SPACE_ID: ${secrets.observability.arize_space_id}

  # =============================================================================
  # SECURITY CONFIGURATION
  # =============================================================================

  JWT_SECRET: ${secrets.security.jwt_secret}
  API_SECRET_KEY: ${secrets.security.api_secret_key}
  NEON_AUTH_JWKS_URL: ${secrets.security.neon_auth_jwks_url}

  # =============================================================================
  # FEATURE FLAGS
  # =============================================================================

  ENABLE_STREAMING: ${config.features.enable_streaming}
  ENABLE_MEMORY: ${config.features.enable_memory}
  ENABLE_TEAMS: ${config.features.enable_teams}
  ENABLE_WORKFLOWS: ${config.features.enable_workflows}
  ENABLE_APPS: ${config.features.enable_apps}
  ENABLE_EVALUATION_GATES: ${config.features.enable_evaluation_gates}
  ENABLE_RUNNER_GATE: ${config.features.enable_runner_gate}
  ENABLE_SAFETY_CHECKS: ${config.features.enable_safety_checks}

  # Development Flags
  USE_REAL_APIS: true
  ENABLE_API_VALIDATION: true
  FAIL_ON_MOCK_FALLBACK: true
  ENABLE_RUNNER_WRITES: ${config.features.enable_runner_writes}
  ENABLE_GIT_WRITES: ${config.features.enable_git_writes}
  ENABLE_FILE_WRITES: ${config.features.enable_file_writes}

  # =============================================================================
  # PERFORMANCE AND COST CONTROLS
  # =============================================================================

  MAX_WORKERS: ${config.performance.max_workers}
  TIMEOUT_SECONDS: ${config.performance.timeout_seconds}
  MAX_RETRIES: ${config.performance.max_retries}
  BATCH_SIZE: ${config.performance.batch_size}
  PARALLEL_REQUESTS: ${config.performance.parallel_requests}

  MAX_TOKENS_PER_REQUEST: ${config.cost_controls.max_tokens_per_request}
  API_RATE_LIMIT: ${config.cost_controls.api_rate_limit}
  API_RATE_WINDOW: ${config.cost_controls.api_rate_window}

  # =============================================================================
  # MODEL CONFIGURATION
  # =============================================================================

  # Default model pools (comma-separated for compatibility)
  DEFAULT_FAST_MODELS: "groq/llama-3.2-90b-text-preview,openai/gpt-4o-mini"
  DEFAULT_BALANCED_MODELS: "openai/gpt-4o,anthropic/claude-3.5-sonnet"
  DEFAULT_HEAVY_MODELS: "anthropic/claude-3.5-sonnet,qwen/qwen-2.5-coder-32b-instruct,openai/gpt-4o"

  # Embedding models
  EMBED_MODEL_TIER_S: ${config.models.embeddings.tier_s}
  EMBED_MODEL_TIER_A: ${config.models.embeddings.tier_a}
  EMBED_MODEL_TIER_B: ${config.models.embeddings.tier_b}

  # =============================================================================
  # ADDITIONAL SERVICE APIs (100+ integrations)
  # =============================================================================

  APIFY_API_TOKEN: ${secrets.services.apify_token}
  APOLLO_IO_API_KEY: ${secrets.services.apollo_api_key}
  ASANA_API_TOKEN: ${secrets.services.asana_token}
  ASSEMBLY_API_KEY: ${secrets.services.assembly_api_key}
  BRIGHTDATA_API_KEY: ${secrets.services.brightdata_key}
  FIGMA_PAT: ${secrets.services.figma_pat}
  HUBSPOT_ACCESS_TOKEN: ${secrets.services.hubspot_token}
  LINEAR_API_KEY: ${secrets.services.linear_api_key}
  NOTION_API_KEY: ${secrets.services.notion_api_key}
  TELEGRAM_API_KEY: ${secrets.services.telegram_api_key}
