name: Codex PR Review (Template)

# NOTE: This is a template. Copy to .github/workflows/codex-review.yml in a
# downstream repo to enable. This repo does not run provider CLIs in CI.

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Codex CLI
        run: npm install -g @codex/cli
      - name: Run GPT-5-Codex review
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
        run: |
          codex review --model gpt-5-codex --format markdown > codex-review.md || true
      - name: Comment review on PR
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { context, core } = require('@actions/github');
            const body = fs.existsSync('codex-review.md') ? fs.readFileSync('codex-review.md', 'utf8') : 'Codex review did not produce output.';
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed('No pull request context.');
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body
              });
            }

