# Comprehensive Swarm Factory Configuration
# Master configuration file for all factory components
version: "1.0.0"
last_updated: "2024-12-19"
environment: "production"

# ============================================================================
# GLOBAL FACTORY SETTINGS
# ============================================================================
factory:
  name: "Sophia-Artemis Intelligent Swarm Factory"
  description: "Comprehensive AI swarm factory integrating mythology and military agents"
  version: "1.0.0"

  # Global limits and constraints
  global_limits:
    max_concurrent_swarms: 10
    max_daily_cost_usd: 100.0
    max_monthly_cost_usd: 2000.0
    default_execution_timeout_minutes: 15
    max_execution_timeout_minutes: 60

  # Cost management
  cost_management:
    enable_cost_tracking: true
    enable_cost_alerts: true
    cost_alert_threshold: 0.8 # Alert at 80% of limit
    daily_budget_reset_hour: 0 # Midnight UTC
    cost_optimization_mode: "balanced" # Options: aggressive, balanced, permissive

  # Quality and performance
  quality_gates:
    min_confidence_threshold: 0.7
    require_consensus_for_critical: true
    enable_performance_monitoring: true
    max_acceptable_response_time_ms: 30000

  # Security and compliance
  security:
    enable_audit_logging: true
    mask_sensitive_data: true
    require_approval_for_high_cost: true
    high_cost_threshold_usd: 10.0

# ============================================================================
# MODEL ROUTING CONFIGURATION
# ============================================================================
model_routing:
  # Default routing preferences
  defaults:
    fallback_enabled: true
    retry_on_failure: true
    max_retries: 3
    cache_responses: true

  # Performance tiers
  performance_tiers:
    premium:
      models: ["openai/gpt-5-chat", "anthropic/claude-3-5-sonnet", "x-ai/grok-5"]
      max_cost_per_1k_tokens: 0.10
      min_context_window: 8000

    balanced:
      models: ["openai/gpt-4o", "anthropic/claude-3-sonnet", "google/gemini-2.0-pro"]
      max_cost_per_1k_tokens: 0.04
      min_context_window: 6000

    efficient:
      models: ["openai/gpt-4o-mini", "anthropic/claude-3-haiku", "groq/llama-3.1-70b"]
      max_cost_per_1k_tokens: 0.015
      min_context_window: 4000

    speed:
      models: ["groq/llama-3.1-70b-versatile", "google/gemini-2.0-flash-exp"]
      max_cost_per_1k_tokens: 0.01
      min_context_window: 4000
      prefer_streaming: true

  # Swarm-specific routing rules
  swarm_routing:
    mythology_strategic:
      performance_tier: "premium"
      agent_role_preferences:
        strategist: ["openai/gpt-5-chat", "anthropic/claude-3-5-sonnet"]
        analyst: ["anthropic/claude-3-opus", "openai/gpt-4o"]
        validator: ["anthropic/claude-3-5-sonnet", "google/gemini-2.0-pro"]

    mythology_analytical:
      performance_tier: "balanced"
      agent_role_preferences:
        analyst: ["anthropic/claude-3-opus", "deepseek/deepseek-chat"]
        validator: ["anthropic/claude-3-sonnet", "openai/gpt-4o"]

    military_tactical:
      performance_tier: "balanced"
      prefer_streaming: true
      agent_role_preferences:
        analyst: ["deepseek/deepseek-coder-v3", "qwen/qwen-3-coder-plus"]
        strategist: ["openai/gpt-4o", "anthropic/claude-3-sonnet"]

    military_recon:
      performance_tier: "efficient"
      prefer_streaming: true
      agent_role_preferences:
        analyst: ["google/gemini-2.0-flash-exp", "groq/llama-3.1-70b-versatile"]

    hybrid_balanced:
      performance_tier: "balanced"
      agent_role_preferences:
        analyst: ["openai/gpt-4o", "anthropic/claude-3-sonnet"]
        strategist: ["anthropic/claude-3-5-sonnet", "google/gemini-2.0-pro"]
        validator: ["anthropic/claude-3-sonnet", "openai/gpt-4o"]

# ============================================================================
# SWARM CONFIGURATIONS
# ============================================================================
swarms:
  # Pre-configured swarm templates
  templates:
    # Mythology Swarms
    sophia_business_intelligence:
      name: "Sophia Business Intelligence Swarm"
      type: "mythology_business"
      coordination_pattern: "sequential"
      agents: ["hermes", "athena", "minerva"]
      max_cost_per_execution: 2.0
      max_execution_time_minutes: 15
      memory_domain: "sophia"
      auto_deliver_results: true
      slack_delivery: "executive_reports"
      tags: ["sophia", "business", "intelligence", "daily"]

    sophia_strategic_planning:
      name: "Sophia Strategic Planning Swarm"
      type: "mythology_strategic"
      coordination_pattern: "debate"
      agents: ["athena", "odin", "minerva"]
      max_cost_per_execution: 3.0
      max_execution_time_minutes: 25
      memory_domain: "sophia"
      auto_deliver_results: true
      slack_delivery: "strategic_analysis"
      tags: ["sophia", "strategy", "planning", "weekly"]

    sophia_business_health:
      name: "Sophia Business Health Diagnostic"
      type: "mythology_health"
      coordination_pattern: "hierarchical"
      agents: ["asclepius", "hermes", "minerva"]
      max_cost_per_execution: 2.5
      max_execution_time_minutes: 20
      memory_domain: "sophia"
      auto_deliver_results: true
      slack_delivery: "executive_reports"
      tags: ["sophia", "health", "diagnostics", "monthly"]

    # Military Swarms
    artemis_reconnaissance:
      name: "Artemis Reconnaissance Battalion"
      type: "military_recon"
      coordination_pattern: "parallel"
      units: ["recon_battalion"]
      max_cost_per_execution: 1.5
      max_execution_time_minutes: 10
      memory_domain: "artemis"
      auto_deliver_results: true
      slack_delivery: "technical_operations"
      tags: ["artemis", "recon", "pathfinders", "scanning"]

    artemis_quality_control:
      name: "Artemis Quality Control Division"
      type: "military_qc"
      coordination_pattern: "hierarchical"
      units: ["qc_division"]
      max_cost_per_execution: 2.0
      max_execution_time_minutes: 15
      memory_domain: "artemis"
      auto_deliver_results: true
      slack_delivery: "code_quality"
      tags: ["artemis", "qc", "sentinels", "validation"]

    artemis_strike_force:
      name: "Artemis Coding Strike Force"
      type: "military_strike"
      coordination_pattern: "hierarchical"
      units: ["strike_force"]
      max_cost_per_execution: 4.0
      max_execution_time_minutes: 30
      memory_domain: "artemis"
      auto_deliver_results: true
      slack_delivery: "technical_operations"
      tags: ["artemis", "strike", "operators", "coding"]

    # Hybrid Swarms
    hybrid_tactical_analysis:
      name: "Hybrid Tactical Analysis Swarm"
      type: "hybrid_tactical"
      coordination_pattern: "consensus"
      max_cost_per_execution: 3.5
      max_execution_time_minutes: 25
      memory_domain: "general"
      auto_deliver_results: true
      slack_delivery: "strategic_analysis"
      tags: ["hybrid", "tactical", "analysis", "consensus"]

# ============================================================================
# DEPLOYMENT CONFIGURATION
# ============================================================================
deployments:
  # Scheduler settings
  scheduler:
    enabled: true
    check_interval_seconds: 60
    max_concurrent_deployments: 5
    cleanup_old_runs_hours: 168 # 7 days

  # Pre-configured deployment schedules
  schedules:
    # Daily schedules
    daily_business_intelligence:
      name: "Daily Business Intelligence Report"
      swarm_template: "sophia_business_intelligence"
      schedule_type: "cron"
      cron_expression: "0 8 * * 1-5" # 8 AM weekdays
      timezone: "UTC"
      enabled: true
      max_daily_runs: 1
      priority: 2
      task_template: "Analyze current business trends, market conditions, and provide strategic insights for today's operations. Include key metrics, opportunities, and recommended actions."

    daily_code_quality:
      name: "Daily Code Quality Assessment"
      swarm_template: "artemis_quality_control"
      schedule_type: "cron"
      cron_expression: "0 9 * * 1-5" # 9 AM weekdays
      timezone: "UTC"
      enabled: true
      max_daily_runs: 1
      priority: 3

    # Weekly schedules
    weekly_strategic_planning:
      name: "Weekly Strategic Planning Session"
      swarm_template: "sophia_strategic_planning"
      schedule_type: "cron"
      cron_expression: "0 9 * * 1" # 9 AM Mondays
      timezone: "UTC"
      enabled: true
      max_daily_runs: 1
      priority: 1
      task_template: "Conduct comprehensive weekly strategic analysis including market trends, competitive landscape, resource allocation, and strategic recommendations for the upcoming week."

    weekly_technical_review:
      name: "Weekly Technical Architecture Review"
      swarm_template: "artemis_reconnaissance"
      schedule_type: "cron"
      cron_expression: "0 14 * * 5" # 2 PM Fridays
      timezone: "UTC"
      enabled: true
      max_daily_runs: 1
      priority: 2

    # Hourly schedules (during business hours)
    hourly_system_monitoring:
      name: "Hourly System Health Monitoring"
      swarm_template: "artemis_reconnaissance"
      schedule_type: "interval"
      interval_minutes: 60
      business_hours_only: true
      start_time: "09:00"
      end_time: "17:00"
      days_of_week: [1, 2, 3, 4, 5] # Monday to Friday
      enabled: true
      max_daily_runs: 8
      priority: 4

  # Event-driven deployments
  event_driven:
    emergency_response:
      name: "Emergency Response System"
      swarm_template: "hybrid_tactical_analysis"
      trigger_events: ["system_alert", "critical_error", "security_breach"]
      priority: 1
      max_concurrent_runs: 3
      timeout_minutes: 5
      enabled: true

# ============================================================================
# SLACK DELIVERY CONFIGURATION
# ============================================================================
slack_delivery:
  # Channel mappings
  channels:
    executive_reports:
      channel_id: "#executive-reports"
      description: "Executive business intelligence and strategic reports"
      audience: ["executives", "leadership"]
      max_messages_per_day: 5
      business_hours_only: false

    strategic_analysis:
      channel_id: "#strategy-insights"
      description: "Strategic analysis and planning insights"
      audience: ["strategy_team", "product_managers"]
      max_messages_per_day: 8
      business_hours_only: true

    technical_operations:
      channel_id: "#artemis-command"
      description: "Technical operations and system status"
      audience: ["developers", "devops", "tech_leads"]
      max_messages_per_day: 15
      business_hours_only: true

    code_quality:
      channel_id: "#code-quality"
      description: "Code quality assessments and recommendations"
      audience: ["developers", "code_reviewers"]
      max_messages_per_day: 12
      business_hours_only: true

    daily_intelligence:
      channel_id: "#daily-intelligence"
      description: "Daily business intelligence and metrics"
      audience: ["business_analysts", "operations"]
      max_messages_per_day: 3
      business_hours_only: true

    critical_alerts:
      channel_id: "#critical-alerts"
      description: "Critical issues requiring immediate attention"
      audience: ["oncall", "sre", "executives"]
      max_messages_per_day: 50
      business_hours_only: false

  # Delivery templates
  templates:
    executive_summary:
      format: "executive"
      priority: "high"
      include_cost: false
      include_reasoning: false
      max_length: 2000
      mention_roles: ["executives"]

    daily_intelligence:
      format: "summary"
      priority: "normal"
      include_cost: true
      include_reasoning: false
      max_length: 3000

    technical_operations:
      format: "technical"
      priority: "normal"
      include_cost: true
      include_reasoning: true
      max_length: 4000
      mention_users: ["tech-leads"]

    strategic_analysis:
      format: "detailed"
      priority: "high"
      include_cost: false
      include_reasoning: true
      max_length: 5000
      mention_roles: ["strategy-team"]

    critical_alerts:
      format: "summary"
      priority: "urgent"
      include_cost: false
      include_reasoning: true
      max_length: 2000
      mention_roles: ["oncall", "sre"]

  # Auto-delivery rules
  auto_delivery_rules:
    - rule_id: "executive_intelligence"
      name: "Executive Intelligence Delivery"
      swarm_types: ["mythology_business", "mythology_strategic"]
      confidence_threshold: 0.85
      keywords: ["business", "strategic", "executive"]
      time_ranges: [{ "start_hour": 7, "end_hour": 9 }, { "start_hour": 17, "end_hour": 19 }]
      delivery_config: "executive_reports"
      enabled: true

    - rule_id: "technical_operations"
      name: "Technical Operations Updates"
      swarm_types: ["military_recon", "military_qc", "military_strike"]
      confidence_threshold: 0.70
      keywords: ["code", "technical", "system", "quality"]
      time_ranges: [{ "start_hour": 9, "end_hour": 17 }]
      delivery_config: "technical_operations"
      enabled: true

    - rule_id: "critical_alerts"
      name: "Critical System Alerts"
      keywords: ["critical", "urgent", "alert", "failure", "error", "breach"]
      confidence_threshold: 0.90
      delivery_config: "critical_alerts"
      enabled: true

# ============================================================================
# MONITORING AND ALERTS
# ============================================================================
monitoring:
  # Performance monitoring
  performance:
    enable_metrics_collection: true
    metrics_retention_days: 30
    alert_on_slow_response: true
    slow_response_threshold_ms: 30000
    alert_on_high_cost: true
    high_cost_threshold_usd: 5.0

  # Health checks
  health_checks:
    interval_minutes: 5
    component_timeouts:
      portkey_manager: 10
      memory_router: 5
      model_routing: 5
      slack_delivery: 10
    failure_threshold: 3 # Failures before alerting

  # Audit logging
  audit:
    enable_audit_log: true
    log_level: "INFO"
    log_retention_days: 90
    log_sensitive_data: false
    log_destinations: ["file", "slack"]

# ============================================================================
# INTEGRATION SETTINGS
# ============================================================================
integrations:
  # Portkey configuration
  portkey:
    config_file: "app/core/portkey_config.yaml"
    enable_caching: true
    cache_ttl_minutes: 60
    retry_attempts: 3
    timeout_seconds: 120

  # Memory system
  memory:
    enable_cross_swarm_memory: true
    memory_retention_days: 30
    enable_learning_from_interactions: true
    confidence_boost_from_memory: 0.1

  # External APIs
  external_apis:
    enable_web_research: true
    web_research_timeout_seconds: 30
    enable_market_data: false
    market_data_provider: null

# ============================================================================
# ENVIRONMENT-SPECIFIC OVERRIDES
# ============================================================================
environments:
  development:
    factory:
      global_limits:
        max_daily_cost_usd: 10.0
        max_monthly_cost_usd: 100.0
    deployments:
      scheduler:
        enabled: false
    monitoring:
      performance:
        alert_on_high_cost: false

  staging:
    factory:
      global_limits:
        max_daily_cost_usd: 25.0
        max_monthly_cost_usd: 500.0
    slack_delivery:
      channels:
        executive_reports:
          channel_id: "#staging-reports"
        critical_alerts:
          channel_id: "#staging-alerts"

  production:
    # Use default configuration
    pass

# ============================================================================
# FEATURE FLAGS
# ============================================================================
feature_flags:
  enable_experimental_swarms: false
  enable_cost_optimization: true
  enable_auto_scaling: false
  enable_advanced_routing: true
  enable_memory_learning: true
  enable_performance_tuning: true
  enable_multi_region: false

# ============================================================================
# METADATA
# ============================================================================
metadata:
  configuration_version: "1.0.0"
  created_by: "Swarm Factory Bootstrap"
  created_at: "2024-12-19T00:00:00Z"
  supported_environments: ["development", "staging", "production"]
  dependencies:
    - "portkey-ai >= 1.0.0"
    - "anthropic >= 0.34.0"
    - "openai >= 1.0.0"
  notes: |
    This is the master configuration for the Sophia-Artemis Intelligent Swarm Factory.
    It integrates mythology agents (Hermes, Athena, etc.) with military-themed swarms
    for comprehensive AI-powered business intelligence and technical operations.

    Key features:
    - Intelligent model routing with cost optimization
    - Automated deployment scheduling
    - Slack integration with rich formatting
    - Comprehensive monitoring and alerting
    - Support for multiple environments

    For deployment-specific configurations, see the environments section.
    For custom swarm configurations, extend the swarms.templates section.
