# ArgoCD Application for KEDA Autoscaling
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-autoscaling
  namespace: argocd
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/part-of: sophia-intel-ai
    app.kubernetes.io/component: autoscaling
  annotations:
    description: "KEDA autoscaling for Sophia Intel AI - Target: 85% improvement (60s to 9s)"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-team
    notifications.argoproj.io/subscribe.on-sync-failed.slack: platform-team
    notifications.argoproj.io/subscribe.on-health-degraded.slack: platform-team
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sophia-intel-ai

  source:
    repoURL: https://github.com/sophia-intel-ai/infrastructure
    targetRevision: HEAD
    path: infrastructure/keda/gitops/overlays/prod # Change based on environment

    # Kustomize configuration
    kustomize:
      namePrefix: ""
      nameSuffix: ""
      commonLabels:
        managed-by: argocd
      images:
        - ghcr.io/kedacore/keda:2.13.0
        - ghcr.io/kedacore/keda-metrics-apiserver:2.13.0

  destination:
    server: https://kubernetes.default.svc
    namespace: keda-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment rules
  ignoreDifferences:
    - group: keda.sh
      kind: ScaledObject
      jsonPointers:
        - /status
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas # Ignore replica count changes from KEDA

  # Revision history
  revisionHistoryLimit: 10

  # Info for tracking
  info:
    - name: "SLA Target"
      value: "85% improvement (60s to 9s)"
    - name: "Circuit Breaker"
      value: "3 events/min max"
    - name: "KEDA Version"
      value: "2.13.0"
---
# AppProject for Sophia Intel AI (if not already exists)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sophia-intel-ai
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sophia-intel-ai
spec:
  description: "Sophia Intel AI Platform"

  sourceRepos:
    - https://github.com/sophia-intel-ai/infrastructure
    - https://kedacore.github.io/charts

  destinations:
    - namespace: keda-system
      server: https://kubernetes.default.svc
    - namespace: sophia-system
      server: https://kubernetes.default.svc
    - namespace: sophia-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: platform-team
      policies:
        - p, proj:sophia-intel-ai:platform-team, applications, *, sophia-intel-ai/*, allow
        - p, proj:sophia-intel-ai:platform-team, repositories, *, *, allow
      groups:
        - platform-team

    - name: developers
      policies:
        - p, proj:sophia-intel-ai:developers, applications, get, sophia-intel-ai/*, allow
        - p, proj:sophia-intel-ai:developers, applications, sync, sophia-intel-ai/*, allow
      groups:
        - developers
---
# ApplicationSet for multi-environment deployment
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda-autoscaling-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://dev.kubernetes.local
            path: infrastructure/keda/gitops/overlays/dev
            namespace: keda-system
            autoSync: true
          - cluster: staging
            url: https://staging.kubernetes.local
            path: infrastructure/keda/gitops/overlays/staging
            namespace: keda-system
            autoSync: true
          - cluster: production
            url: https://production.kubernetes.local
            path: infrastructure/keda/gitops/overlays/prod
            namespace: keda-system
            autoSync: false # Manual sync for production

  template:
    metadata:
      name: "keda-{{cluster}}"
      namespace: argocd
      labels:
        environment: "{{cluster}}"
        app.kubernetes.io/name: keda
        app.kubernetes.io/part-of: sophia-intel-ai
      annotations:
        description: "KEDA autoscaling for {{cluster}} environment"
    spec:
      project: sophia-intel-ai

      source:
        repoURL: https://github.com/sophia-intel-ai/infrastructure
        targetRevision: HEAD
        path: "{{path}}"

      destination:
        server: "{{url}}"
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: "{{autoSync}}"
          selfHeal: "{{autoSync}}"
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      revisionHistoryLimit: 10
