# Default values for sophia-artemis
global:
  domain: sophia-artemis.local
  environment: production
  imagePullSecrets: []

# Istio configuration
istio:
  enabled: true
  version: 1.20.0
  namespace: istio-system
  controlPlane:
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 4096Mi
  gateway:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  mtls:
    mode: STRICT
  telemetry:
    v2:
      prometheus:
        enabled: true
      tracing:
        enabled: true
        sampling: 100.0

# Artemis domain configuration
artemis:
  enabled: true
  namespace: artemis-mesh
  orchestrator:
    image:
      repository: sophia-artemis/artemis-orchestrator
      tag: latest
      pullPolicy: Always
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    maxConcurrentTasks: 8
    env:
      LOG_LEVEL: info
      ISTIO_ENABLED: "true"
    canary:
      enabled: false
      replicas: 1
      image:
        tag: canary
    config:
      taskTimeout: 300s
      retryPolicy:
        maxAttempts: 3
        backoffMultiplier: 2
    mcp:
      servers:
        - filesystem
        - sqlite
        - git
        - github
        - puppeteer
      connectionPoolSize: 10
      requestTimeout: 30s

# Sophia domain configuration
sophia:
  enabled: true
  namespace: sophia-mesh
  orchestrator:
    image:
      repository: sophia-artemis/sophia-orchestrator
      tag: latest
      pullPolicy: Always
    replicas: 3
    resources:
      requests:
        cpu: 750m
        memory: 1.5Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 12
      targetCPUUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 75
    maxConcurrentTasks: 8
    env:
      LOG_LEVEL: info
      ISTIO_ENABLED: "true"
    experimental:
      enabled: false
      replicas: 1
      image:
        tag: experimental
    config:
      taskTimeout: 600s
      retryPolicy:
        maxAttempts: 3
        backoffMultiplier: 2
    mcp:
      servers:
        - postgres
        - sqlite
        - slack
        - google-maps
      connectionPoolSize: 15
      requestTimeout: 60s
    dataProcessing:
      batchSize: 1000
      parallelism: 4
      checkpointInterval: 60s
      errorThreshold: 0.05

# Shared services configuration
sharedServices:
  enabled: true
  namespace: shared-services
  memory:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  config:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  logging:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  metrics:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Traffic management
trafficManagement:
  gateway:
    enabled: true
    hosts:
      artemis: artemis.sophia-artemis.local
      sophia: sophia.sophia-artemis.local
      api: api.sophia-artemis.local
      admin: admin.sophia-artemis.local
    tls:
      enabled: true
      credentialName: sophia-artemis-tls
  rateLimit:
    enabled: true
    globalLimit: 1000
    perServiceLimit: 100
    concurrentTaskLimit: 8
  circuitBreaker:
    enabled: true
    consecutiveErrors: 5
    interval: 30s
    baseEjectionTime: 30s
    maxEjectionPercent: 50
  canary:
    enabled: false
    strategy: gradual
    incrementPercentage: 10
    incrementInterval: 5m
    successThreshold: 0.95
    rollbackThreshold: 0.90

# Security configuration
security:
  mtls:
    enabled: true
    mode: STRICT
  authorization:
    enabled: true
    rbac:
      enabled: true
  certificates:
    autoRotation: true
    validityDays: 365
    renewBeforeDays: 30
  crossDomain:
    enabled: true
    requireToken: true
    allowedFlows:
      - from: artemis-mesh
        to: shared-services
      - from: sophia-mesh
        to: shared-services
      - from: artemis-mesh
        to: sophia-mesh
        restricted: true
      - from: sophia-mesh
        to: artemis-mesh
        restricted: true

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
    retention: 15d
    storageSize: 50Gi
    scrapeInterval: 15s
  grafana:
    enabled: true
    adminPassword: changeme
    dashboards:
      artemisPerformance: true
      sophiaBusinessMetrics: true
      crossDomainFlow: true
  tracing:
    enabled: true
    zipkin:
      enabled: true
      storageType: memory
  kiali:
    enabled: true
    createDemoSecret: false
    dashboard:
      auth:
        strategy: anonymous

# External services
externalServices:
  redis:
    enabled: true
    host: redis.cache.local
    port: 6379
  postgres:
    enabled: false
    host: postgres.database.local
    port: 5432
  rabbitmq:
    enabled: false
    host: rabbitmq.messaging.local
    port: 5672

# Resource allocations
resources:
  istioProxy:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Pod disruption budgets
podDisruptionBudget:
  artemis:
    minAvailable: 2
  sophia:
    minAvailable: 2
  sharedServices:
    minAvailable: 1

# Node affinity preferences
nodeAffinity:
  preferredZones:
    - us-west-2a
    - us-west-2b
    - us-west-2c

# Topology spread constraints
topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  whenUnsatisfiable: DoNotSchedule
