apiVersion: v2
name: sophia-intel-ai
description: A Helm chart for Sophia Intel AI Platform - Production-Ready AI Orchestration System
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - ai
  - machine-learning
  - orchestration
  - automation
  - microservices

home: https://github.com/sophia-intel-ai
sources:
  - https://github.com/sophia-intel-ai

maintainers:
  - name: Sophia Intel AI Team
    email: team@sophia-intel-ai.com

annotations:
  category: AI/ML Platform
  licenses: MIT

dependencies:
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus
    version: 19.6.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
