app = "sophia-mcp"            # Fly app for MCP gateway/service
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"   # Adjust if MCP has its own Dockerfile

[deploy]
  strategy = "bluegreen"

[processes]
  # TODO: Replace with the actual MCP server command
  web = "uvicorn mcp.gateway:app --host 0.0.0.0 --port 8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
    grace_period = "15s"

