# Fly.io config for the Sophia Intel UI (Next.js on port 3000)
app = "sophia-ui"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "infra/Dockerfile.sophia-intel-app"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NEXT_PUBLIC_API_BASE = "https://sophia-api.fly.dev"

[services]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 150
    soft_limit = 100

  [[services.http_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"

[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  web = "npm start --prefix sophia-intel-app"

