# Fly.io config for the unified Sophia API (port 8000)
app = "sophia-api"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "infra/Dockerfile.unified"

[env]
  PORT = "8000"

[services]
  protocol = "tcp"
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.http_checks]]
    interval = "15s"
    timeout = "3s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[processes]
  app = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
