# Artemis Application - Points to existing Artemis deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artemis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sophia-intel-ai/infrastructure
    targetRevision: HEAD
    path: k8s/artemis
  destination:
    server: https://kubernetes.default.svc
    namespace: artemis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
