# KEDA Application - Points to existing KEDA configurations
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sophia-intel-ai/infrastructure
    targetRevision: HEAD
    path: infrastructure/keda/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: keda-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
