# Model Configuration - Latest and Greatest Models
# You can customize which models to use for each provider

providers:
  claude:
    models:
      - id: "claude-3-5-sonnet-20241022"
        name: "Claude 3.5 Sonnet (Latest)"
        default: true
        max_tokens: 8192
      - id: "claude-3-5-haiku-20241022"
        name: "Claude 3.5 Haiku (Fast)"
        max_tokens: 8192
      - id: "claude-3-opus-20240229"
        name: "Claude 3 Opus (Powerful)"
        max_tokens: 4096

  openai:
    models:
      - id: "gpt-4o"
        name: "GPT-4o (Latest)"
        default: true
        max_tokens: 128000
      - id: "gpt-4o-mini"
        name: "GPT-4o Mini (Fast)"
        max_tokens: 128000
      - id: "o1-preview"
        name: "o1 Preview (Reasoning)"
        max_tokens: 32768
      - id: "o1-mini"
        name: "o1 Mini (Fast Reasoning)"
        max_tokens: 65536

  deepseek:
    models:
      - id: "deepseek-coder-v3"
        name: "DeepSeek Coder V3 (Latest)"
        default: true
        max_tokens: 16384
      - id: "deepseek-chat"
        name: "DeepSeek Chat"
        max_tokens: 16384

  qwen:
    models:
      - id: "qwen2.5-coder-32b-instruct"
        name: "Qwen 2.5 Coder 32B (Latest)"
        default: true
        max_tokens: 32768
      - id: "qwen-max"
        name: "Qwen Max"
        max_tokens: 32768
      - id: "qwen-plus"
        name: "Qwen Plus"
        max_tokens: 32768

  openrouter:
    # OpenRouter can access many models
    favorites:
      - "anthropic/claude-3-5-sonnet-20241022"
      - "openai/gpt-4o"
      - "google/gemini-2.0-flash-exp:free"
      - "meta-llama/llama-3.1-405b-instruct"
      - "deepseek/deepseek-coder-v3"
      - "perplexity/llama-3.1-sonar-huge-128k-online"
      - "x-ai/grok-2-1212"
      - "mistralai/mistral-large-2411"

# Model selection presets for different tasks
presets:
  best_overall:
    claude: "claude-3-5-sonnet-20241022"
    openai: "gpt-4o"
    deepseek: "deepseek-coder-v3"
    qwen: "qwen2.5-coder-32b-instruct"
    
  fast_responses:
    claude: "claude-3-5-haiku-20241022"
    openai: "gpt-4o-mini"
    deepseek: "deepseek-chat"
    qwen: "qwen-plus"
    
  reasoning:
    claude: "claude-3-opus-20240229"
    openai: "o1-preview"
    deepseek: "deepseek-coder-v3"
    qwen: "qwen-max"
    
  coding:
    claude: "claude-3-5-sonnet-20241022"
    openai: "gpt-4o"
    deepseek: "deepseek-coder-v3"
    qwen: "qwen2.5-coder-32b-instruct"