---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    istio-injection: disabled
    app.kubernetes.io/managed-by: argocd
  annotations:
    prometheus.io/scrape: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-apps
  labels:
    name: argocd-apps
    app.kubernetes.io/managed-by: argocd
  annotations:
    description: "Namespace for ArgoCD Application resources"
