apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
  labels:
    app: alertmanager
    component: monitoring
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sophia-intel-ai/infrastructure
    targetRevision: HEAD
    path: infrastructure/alertmanager/gitops/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  # Health assessment for AlertManager resources
  health:
    progressDeadlineSeconds: 600

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-staging
  namespace: argocd
  labels:
    app: alertmanager
    component: monitoring
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sophia-intel-ai/infrastructure
    targetRevision: HEAD
    path: infrastructure/alertmanager/gitops/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m

  revisionHistoryLimit: 5

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-dev
  namespace: argocd
  labels:
    app: alertmanager
    component: monitoring
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sophia-intel-ai/infrastructure
    targetRevision: HEAD
    path: infrastructure/alertmanager/gitops/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  revisionHistoryLimit: 3

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alertmanager-project
  namespace: argocd
spec:
  description: AlertManager monitoring infrastructure

  # Source repositories
  sourceRepos:
    - https://github.com/sophia-intel-ai/infrastructure

  # Destination clusters and namespaces
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: monitoring-staging
      server: https://kubernetes.default.svc
    - namespace: monitoring-dev
      server: https://kubernetes.default.svc

  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding

  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Roles
  roles:
    - name: admin
      policies:
        - p, proj:alertmanager-project:admin, applications, *, alertmanager-project/*, allow
      groups:
        - sophia-intel-ai:admins

    - name: readonly
      policies:
        - p, proj:alertmanager-project:readonly, applications, get, alertmanager-project/*, allow
      groups:
        - sophia-intel-ai:developers
