# Draft parallel resources for Sophia orchestrator (non-destructive; do not auto-apply)
# Apply selectively when ready to cut over from legacy Sophia labels/names.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-orchestrator
  labels:
    app.kubernetes.io/name: sophia-orchestrator
    app.kubernetes.io/component: sophia-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: sophia-orchestrator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sophia-orchestrator
    spec:
      containers:
        - name: sophia-orchestrator
          image: sophia-intel-ai/sophia-orchestrator:latest # TODO: confirm image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
            # Portkey is the only LLM gateway
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-orchestrator-service
  labels:
    app.kubernetes.io/name: sophia-orchestrator
    app.kubernetes.io/component: sophia-orchestrator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: sophia-orchestrator
  ports:
    - name: http
      port: 8000
      targetPort: 8000
