# Development environment overrides for KEDA
# Inherits from values.yaml and overrides specific settings

global:
  environment: development

# Reduced resource limits for dev
keda:
  resources:
    operator:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 64Mi
    metricsApiServer:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 64Mi

# More aggressive scaling for testing
scalers:
  sophia:
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 5
    cooldownPeriod: 15
    metadata:
      listLength: "5"
      activationListLength: "1"

  sophia:
    minReplicaCount: 1
    maxReplicaCount: 15
    pollingInterval: 10
    cooldownPeriod: 20
    metadata:
      threshold: "50"
      activationThreshold: "10"

  aiWorkloadCron:
    metadata:
      schedules:
        - name: dev-testing
          start: "0 9 * * 1-5"
          end: "0 17 * * 1-5"
          desiredReplicas: "3"

  # Enable debug logging (merged with keda section above)
  logging:
    operator:
      level: debug
    metricServer:
      level: debug

# Relaxed circuit breaker for testing
circuitBreaker:
  maxScaleEventsPerMinute: 10
  cooldownPeriod: 30s
  errorThreshold: 10

# Disable some security features for easier debugging
security:
  networkPolicy:
    enabled: false

# Use mock secrets for development
externalSecrets:
  backend: kubernetes
  secrets:
    - name: redis-auth
      namespace: sophia-system
      data:
        - key: password
          value: "dev-redis-password"
    - name: prometheus-auth
      namespace: sophia-system
      data:
        - key: token
          value: "dev-prometheus-token"
