name: branch-report

on:
  schedule:
    - cron: '30 6 * * 1' # Mondays at 06:30 UTC
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List branches
        run: |
          echo "Remote branches (excluding main):"
          git ls-remote --heads origin | awk '{print $2}' | sed 's#refs/heads/##' | grep -vE '^(main|legacy-main)$' || true
      - name: List open PRs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.pulls.list({ owner: context.repo.owner, repo: context.repo.repo, state: 'open' })
            core.info(`Open PRs: ${prs.length}`)
            for (const pr of prs) {
              core.info(`#${pr.number} ${pr.title} [${pr.base.ref} <- ${pr.head.ref}]`)  
            }
