name: CI

on:
  push:
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies (best-effort)
        run: |
          set -e
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          pip install pytest ruff || true

      - name: Run pytest if tests exist
        run: |
          if [ -d tests ]; then
            echo "Running pytest..."
            pytest -q || pytest -q -k "" || true
          else
            echo "No tests directory; skipping."
          fi

      - name: Python lint (ruff) if config present
        run: |
          if [ -f ruff.toml ] || [ -f pyproject.toml ]; then
            echo "Running ruff..."
            ruff check . || true
          else
            echo "No ruff config; skipping."
          fi

  node-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Node project and run tests
        run: |
          if [ -f package.json ]; then
            echo "Node project detected. Running tests..."
            corepack enable || true
            if [ -f package-lock.json ]; then npm ci || npm install; else npm install; fi
            npm test || echo "npm test failed or not defined; continuing."
            if npm run | grep -q " lint"; then npm run lint || true; fi
          else
            echo "No package.json; skipping Node tests."
          fi
