name: Docs and Evals
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Link check
        run: python3 scripts/docs/link_check.py
      - name: Run evals (baseline)
        run: python3 scripts/evals/run_evals.py
