name: No-Artemis Guard
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for legacy Artemis references (strict)
        run: |
          python3 scripts/audit/find_legacy_artemis.py --strict
          echo "✅ No legacy Artemis references found."
