name: no-provider-sdks

on:
  pull_request:
  push:

jobs:
  guard-provider-sdks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Forbid direct provider SDK imports in runtime
        run: |
          set -euo pipefail
          # Allow docs/** and examples/**
          MATCHES=$(rg -n "\b(import|from)\s+(openai|anthropic|google\.generativeai|cohere|mistralai|ai21|bedrock|vertexai)\b" \
            app backend services mcp sophia_cli --glob '!**/tests/**' --glob '!**/docs/**' --glob '!**/examples/**' || true)
          if [ -n "$MATCHES" ]; then
            echo "❌ Direct provider SDK imports detected (Portkey-only policy):" && echo "$MATCHES" && exit 1
          fi
          echo "✅ No direct provider SDK imports in runtime paths"

