name: No-UI-and-No-LiteLLM Guard

on:
  pull_request:
  push:

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Fail on forbidden content (runtime/config only)
        run: |
          echo "Scanning for forbidden content..."
          PATTERN='(builder-agno-system|sophia-intel-app(?!/external)|litellm|/frontend\b|webui/|next\.config\.(js|mjs|ts)|vite\.config\.(js|mjs|ts)|mcp/filesystem\.py\b|mcp/git_server\.py\b|npx\s+create-sophia-intel-app|http://localhost:4000|:8090|api\.x\.ai|\bXAI_API_KEY\b|\bgrok\b(?!.*EXTERNAL_TOOLS))'
          forbidden=$(rg -n "$PATTERN" -S --hidden --glob '!**/.git/**' --glob '!docs/**' || true)
          if [ -n "$forbidden" ]; then
            echo "❌ Forbidden content found:" && echo "$forbidden"
            exit 2
          fi
          echo "✅ No forbidden content detected"
