name: Close stale issues and PRs

on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  pull-requests: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 10
          days-before-close: 14
          stale-issue-message: >
            This issue has been marked stale due to inactivity. It will be closed in 4 days unless there is further activity.
          stale-pr-message: >
            This PR has been marked stale due to inactivity. It will be closed in 4 days unless there is further activity.
          close-issue-message: >
            Closing due to inactivity. Please reopen if still relevant.
          close-pr-message: >
            Closing due to inactivity. Please reopen or rebase on main if still relevant.
          exempt-issue-labels: 'pinned,security,release'
          exempt-pr-labels: 'pinned,security,release'
