name: UI Tests

on:
  push:
    branches: [main]
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yml'
  pull_request:
    branches: [main]
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Install Playwright browsers
        run: pnpm dlx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ui/playwright-report/
          retention-days: 30

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ui/.next/
          retention-days: 7

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    
    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.startServerCommand="pnpm start" --collect.url="http://localhost:3000" --assert.preset="lighthouse:recommended" --assert.assertions.categories:performance=["error", {"minScore": 0.85}] --assert.assertions.categories:accessibility=["error", {"minScore": 0.85}] --assert.assertions.categories:best-practices=["error", {"minScore": 0.85}] || true

      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: ui/.lighthouseci/
          retention-days: 7