tasks:
  planning:
    provider: openrouter
    model: x-ai/grok-4  # PRIMARY: Grok for strategic planning
    fallback:
      provider: openrouter  
      model: openai/gpt-5-turbo  # SECONDARY: GPT-5 fallback
      
  generation:
    provider: openrouter
    model: x-ai/grok-code-fast-1  # PRIMARY: Grok code generation
    fallback:
      provider: aimlapi
      model: qwen/qwen3-max  # SECONDARY: Qwen3 Max fallback
      
  validation:
    provider: aimlapi
    model: qwen/qwen3-max  # PRIMARY: Qwen3 Max for validation
    fallback:
      provider: openrouter
      model: openai/gpt-5-turbo  # SECONDARY: GPT-5 fallback
      
  orchestration:  # NEW: For Artemis Supreme
    provider: openrouter
    model: x-ai/grok-4  # Grok-4 as the supreme orchestrator brain
    budget_limit: 100.00
    priority: maximum
    temperature: 0.1
    
  swarm_coordination:  # NEW: Multi-agent coordination
    provider: openrouter
    model: x-ai/grok-code-fast-1
    temperature: 0.1  # Low temperature for precise coordination
    
  deep_research:  # NEW: Web search and analysis
    provider: aimlapi
    model: qwen/qwen3-max
    context_window: 128000
    
  # Reduced Claude usage to specific specialized tasks
  code_review:  # Only for critical review tasks
    provider: anthropic
    model: claude-3.5-sonnet
    fallback:
      provider: openrouter
      model: x-ai/grok-4
      
  indexing:
    provider: aimlapi
    model: qwen/qwen3-max  # Upgraded from GLM
    
  vision:
    provider: aimlapi
    model: flux-pro/v1.1
